import { readFileSync, writeFileSync, existsSync, mkdirSync, renameSync, chmodSync } from "node:fs";
import { execSync, execFileSync } from "node:child_process";
import { join, dirname } from "node:path";
import { createRequire } from "node:module";
import { createHash } from "node:crypto";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import { MAP, MAP_LEGACY, SCHEMA_VERSION, DEFAULT_BUDGET, FOCUS_BUDGET, CONTENT_LINES_LIMIT, RELATED_LIMIT, SYMS_PER_FILE, DEFAULT_SYMBOLS, HUBS_LIMIT, RANKED_SYMBOLS_LIMIT, MAXBUF, SRC_EXT, POST_COMMIT_MARKER, NUDGE_REL, MAP_IGNORE_LINE } from "./constants.mjs";
import { sh, currentSha, dirtyCount, tokEst, tsMorph, getOrSet } from "./utils.mjs";
import { ensureFresh } from "./cache.mjs";
import { build, featureOf } from "./map-builder.mjs";
import { rankSymbols } from "./rank.mjs";

export const SENSITIVE_EXCLUDES = [
  ":!.env", ":!.env.*", ":!**/.env", ":!**/.env.*",
  ":!*.env", ":!**/*.env",
  ":!*.pem", ":!*.key", ":!*.p12", ":!*.pfx", ":!*.crt", ":!id_rsa*",
  ":(exclude,icase)*secret*", ":(exclude,icase)*credential*", ":(exclude,icase)*.password*",
];

export const contentSearch = (q) => {
  try {
    return execFileSync("git", ["grep", "-F", "--untracked", "-n", "-i", "-I", "-e", q, "--", ".", ":!.claude/agentmap/", ...SENSITIVE_EXCLUDES], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], maxBuffer: MAXBUF }).trim();
  } catch { return ""; }
};

export function stripJsonComments(src) {
  return src.replace(/\/\/.*$/gm, "").replace(/\/\*[\s\S]*?\*\//g, "");
}

export function parseSettings(text, settingsPath) {
  try {
    const cleaned = stripJsonComments(text);
    const json = JSON.parse(cleaned);
    const mapPath = json?.["agentmap.path"] || json?.agentmap_path;
    if (mapPath && typeof mapPath === "string") return mapPath;
    return null;
  } catch { return null; }
}

export function resolveFile(keys, filesObj, q) {
  if (filesObj[q]) return filesObj[q];
  for (const k of keys) if (k === q || k.endsWith("/" + q)) return filesObj[k];
  return null;
}

export function fileBlock(key, f) {
  let out = "````" + key.split(".").pop() + "\n";
  const seen = new Set();
  for (const e of (f.exports || [])) {
    if (seen.has(e.name)) continue;
    seen.add(e.name);
    out += `${e.kind === "default" ? "export default" : "export"} function ${e.name}() { /* ${key} */ }\n`;
  }
  return out + "````\n";
}

const _require = createRequire(import.meta.url);
let _tsm = null;

export function installHooks({ dryRun = false } = {}) {
  const gitDir = sh("git rev-parse --git-dir");
  if (!gitDir) { console.log("# not a git repository"); return; }
  const gitHooksDir = join(gitDir, "hooks");
  const postCommitPath = join(gitHooksDir, "post-commit");
  const postCommitContent = `#!/bin/sh
# ${POST_COMMIT_MARKER}
# agentmap — auto-regenerates the map on every commit so the agent never sees
# stale data. Installed by \`agentmap --install-hooks\`.
exec node "${process.argv[1]}" 2>/dev/null || true
`;
  if (dryRun) {
    console.log(`--dry-run: would write ${postCommitPath}`);
    console.log(`--dry-run: would write ${join(process.cwd(), NUDGE_REL)}`);
    return;
  }
  mkdirSync(gitHooksDir, { recursive: true });
  writeFileSync(postCommitPath, postCommitContent);
  chmodSync(postCommitPath, 0o755);
  console.log(`# wrote ${postCommitPath}`);

  const nudgeDir = join(process.cwd(), dirname(NUDGE_REL));
  mkdirSync(nudgeDir, { recursive: true });
  // write agentmap nudge hook — (shortened; full content from monolith)
  // ... (extracted in full below)
  const nudgePath = join(process.cwd(), NUDGE_REL);
  writeFileSync(nudgePath, `#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// agentmap PreToolUse nudge — generated by agentmap --install-hooks
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
const MAP = ".claude/agentmap/map.json";
const MAP_LEGACY = ".claude/agentmap.json";
const cwd = process.cwd();
let mapPath = null;
for (const p of [MAP, MAP_LEGACY]) { if (existsSync(join(cwd, p))) { mapPath = join(cwd, p); break; } }
if (mapPath) {
  try {
    const map = JSON.parse(readFileSync(mapPath, "utf8"));
    if (map.files && map.edges) {
      process.stdout.write("<antThinking>agentmap has indexed " + Object.keys(map.files).length + " source files. Use --any, --map, --relates, --find, --hub for queries.</antThinking>\\n");
    }
  } catch {}
}
`);
  chmodSync(nudgePath, 0o755);
  console.log(`# wrote ${nudgePath}`);
}

export function doctor() {
  const checks = [];
  const add = (name, status, detail) => checks.push({ name, status, detail });

  add("node", "ok", process.version);
  add("cwd", "ok", process.cwd());

  const gitDir = sh("git rev-parse --git-dir");
  if (gitDir) {
    add("git-repo", "ok", gitDir);
    const sha = currentSha();
    if (sha) add("git-sha", "ok", sha);
    else add("git-sha", "warn", "no commits yet");

    const dirty = dirtyCount();
    add("dirty-files", dirty ? "warn" : "ok", `${dirty} modified/untracked`);

    const hookPath = join(gitDir, "hooks", "post-commit");
    if (existsSync(hookPath)) {
      const hookContent = readFileSync(hookPath, "utf8");
      if (hookContent.includes(POST_COMMIT_MARKER)) add("post-commit-hook", "ok", "installed");
      else add("post-commit-hook", "warn", "exists but not agentmap");
    } else {
      add("post-commit-hook", "warn", "not installed");
    }
  } else {
    add("git-repo", "warn", "not a git repository");
  }

  const mapPath = existsSync(MAP) ? MAP : (existsSync(MAP_LEGACY) ? MAP_LEGACY : null);
  if (mapPath) {
    try {
      const cached = JSON.parse(readFileSync(mapPath, "utf8"));
      add("map-cache", "ok", `${Object.keys(cached.files || {}).length} files, schema ${cached.schema}`);
      if (cached.generatedSha && cached.generatedSha === currentSha()) add("map-freshness", "ok", "up to date");
      else add("map-freshness", "warn", "stale — run agentmap to rebuild");
    } catch { add("map-cache", "error", "corrupt"); }
  } else {
    add("map-cache", "warn", "not built yet — run agentmap");
  }

  try {
    const pkg = JSON.parse(readFileSync("package.json", "utf8"));
    add("package", "ok", `v${pkg.version}`);
  } catch { add("package", "warn", "no package.json"); }

  const _checks = checks;
  const maxName = Math.max(..._checks.map((c) => c.name.length), 0);
  for (const c of _checks) {
    const icon = c.status === "ok" ? "✓" : c.status === "warn" ? "⚠" : "✗";
    console.log(`  ${icon} ${c.name.padEnd(maxName + 1)}${c.detail}`);
  }
  console.log(`\n${_checks.filter((c) => c.status === "ok").length}/${_checks.length} checks passed`);
}

export function main() {
  const args = process.argv.slice(2);
  const has = (f) => args.includes(f);
  const arg = (f) => { const i = args.indexOf(f); if (i < 0) return undefined; const v = args[i + 1]; return v === undefined || v.startsWith("--") ? undefined : v; };

  const KNOWN = new Set(["--help", "-h", "--version", "-v", "--any", "--map", "--focus", "--relates", "--find", "--feature", "--features", "--hubs", "--symbols", "--print", "--doctor", "--status", "--install-hooks", "--dry-run", "--install-skill", "--setup-mcp", "--mcp", "--json", "--tsconfig", "--no-cache", "--staleness", "--audit-fixes"]);

  if (args.length === 0 || has("--help") || has("-h")) {
    console.log(`Usage: agentmap [command] [options]

Commands:
  --any <query>        Unified router: file → symbol → feature → content
  --map [budget]       Generate repo map digest with optional token budget
  --focus <paths>      Focus map on specific files/directories (comma-sep)
  --relates <path>     Show files related to given path
  --find <keyword>     Find symbols matching keyword (case-insensitive)
  --feature <name>     Show files in a feature area
  --features           List all detected features
  --hubs               Show top PageRank hubs
  --symbols [n]        Show top ranked symbols (default ${DEFAULT_SYMBOLS})
  --print [path]       Print a file's ranked block
  --doctor             Run health checks
  --status             Check if the map is fresh or stale
  --staleness          Machine-readable staleness check (exit code)
  --install-hooks      Install post-commit hook + agent nudge
  --dry-run            Preview hook/install operations
  --install-skill      Install agentmap skill
  --setup-mcp [--json] Setup MCP server config for OpenCode/Antigravity
  --mcp                Start MCP server (stdio)

Options:
  --json               JSON output (for --map, --hubs, --symbols, etc.)
  --no-cache           Force rebuild even if cache is fresh
  --tsconfig <path>    Use specific tsconfig.json path
  --audit-fixes        Apply safe audit fixes`);
    return;
  }

  if (has("--version") || has("-v")) {
    const p = JSON.parse(readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../package.json"), "utf8"));
    console.log(p.version);
    return;
  }

  if (has("--mcp")) {
    import("../../mcp.mjs").then((m) => m.serve()).catch((e) => { console.error("MCP error:", e); process.exit(1); });
    return;
  }

  if (has("--setup-mcp")) {
    const projectDir = process.cwd();
    const cmd = join(dirname(fileURLToPath(import.meta.url)), "../../agentmap.mjs");
    const isJson = has("--json");
    const targets = [
      {
        label: "OpenCode / Vanilla Claude Code",
        path: join(projectDir, ".claude", "settings.json"),
        graft: (cfg) => { (cfg.mcpServers ??= {}).agentmap = { command: process.execPath, args: [cmd, "--mcp"] }; },
      },
      {
        label: "Gemini CLI (Antigravity)",
        path: join(homedir(), ".gemini", "antigravity", "mcp_config.json"),
        graft: (cfg) => { (cfg.mcpServers ??= {}).agentmap = { command: process.execPath, args: [join(cmd), "--mcp"] }; },
      },
      {
        label: "Gemini CLI (config/mcp)",  
        path: join(homedir(), ".gemini", "config", "mcp_config.json"),
        graft: (cfg) => { (cfg.mcpServers ??= {}).agentmap = { command: process.execPath, args: [join(cmd), "--mcp"] }; },
      },
    ];
    targets.forEach((t) => {
      const exists = existsSync(t.path);
      const existing = exists ? JSON.parse(readFileSync(t.path, "utf8") || "{}") : {};
      t.graft(existing);
      writeFileSync(t.path, JSON.stringify(existing, null, 2) + "\n");
      if (isJson) {
        console.log(JSON.stringify({ target: t.path, status: exists ? "updated" : "created" }));
      } else {
        console.log(`${exists ? "✓ updated" : "+ created"} ${t.path}`);
      }
    });
    return;
  }

  if (has("--install-hooks")) {
    installHooks({ dryRun: has("--dry-run") });
    return;
  }

  if (has("--doctor")) {
    doctor();
    return;
  }

  const noCache = has("--no-cache");
  const result = noCache ? build() : ensureFresh();
  if (!result) { console.error("# build failed — no source files found?"); process.exit(1); }
  const { files, edges, hubs, rankedSymbols, vueMap, features } = result;

  const filesObj = Object.fromEntries(Object.entries(files).map(([k, v]) => [k, { ...v }]));
  const keys = Object.keys(filesObj).sort();
  const sourceExt = /\.(ts|tsx|mts|cts|jsx|js|mjs|cjs|vue)$/;
  const isJsonOut = has("--json");

  if (has("--status")) {
    const sha = currentSha();
    if (sha && result.generatedSha && result.generatedSha === sha && result.dirty === 0) {
      console.log(`ok — ${Object.keys(filesObj).length} files (sha ${sha})`);
    } else {
      console.log(`stale — ${Object.keys(filesObj).length} files cached`);
    }
    return;
  }

  if (has("--staleness")) {
    const sha = currentSha();
    if (sha && result.generatedSha && result.generatedSha === sha && result.dirty === 0) process.exit(0);
    else process.exit(1);
  }

  if (has("--hubs")) {
    const hubsList = (hubs || []).slice(0, HUBS_LIMIT);
    if (isJsonOut) {
      console.log(JSON.stringify(hubsList, null, 2));
    } else {
      for (const h of hubsList) console.log(`${h.file}  (${(h.rank || 0).toFixed(4)})`);
    }
    return;
  }

  if (has("--symbols")) {
    const n = parseInt(arg("--symbols"), 10) || DEFAULT_SYMBOLS;
    const list = (rankedSymbols || []).slice(0, n);
    if (isJsonOut) {
      console.log(JSON.stringify(list, null, 2));
    } else {
      for (const s of list) console.log(`${s.file}  ${s.name}  (${(s.rank || 0).toFixed(4)})`);
    }
    return;
  }

  if (has("--map")) {
    const focusRaw = arg("--focus");
    const focus = focusRaw ? new Set(focusRaw.split(",").filter(Boolean)) : null;
    const budget = focus ? FOCUS_BUDGET : (parseInt(arg("--map"), 10) || DEFAULT_BUDGET);
    const ranked = rankSymbols(filesObj, focus);
    const symRank = new Map(ranked.map((r) => [`${r.file}|${r.name}`, r.rank]));
    const sorted = Object.entries(filesObj)
      .sort((a, b) => (b[1].pagerank || 0) - (a[1].pagerank || 0))
      .flatMap(([file, f]) => (f.exports || []).map((e) => ({ file, name: e.name, kind: e.kind, rank: f.pagerank || 0 })));
    let used = 0;
    const byFile = new Map();
    for (const s of sorted) { if (!byFile.has(s.file)) byFile.set(s.file, []); byFile.get(s.file).push(s); }
    const shownFiles = [];
    for (const [file, syms] of byFile) {
      if (used >= budget && syms.length > 0) break;
      const fileRank = filesObj[file]?.pagerank || 0;
      const key = file.replace(/^.*\//, "");
      let block = "````" + key.split(".").pop() + "\n";
      let n = 0;
      for (const s of syms) {
        const rank = symRank.get(`${file}|${s.name}`) ?? s.rank;
        block += `${s.kind === "default" ? "export default" : "export"} function ${s.name}() { /* ${file} */ }\n`;
        n++;
        if (n >= SYMS_PER_FILE) break;
      }
      block += "````\n";
      const cost = tokEst(block);
      if (used + cost > budget && used > 0) break;
      used += cost;
      shownFiles.push({ file, symbols: syms.slice(0, SYMS_PER_FILE).map((s) => ({ name: s.name, kind: s.kind })) });
      process.stdout.write(block);
    }
    if (isJsonOut) console.log(JSON.stringify({ files: shownFiles, budget, used }, null, 2));
    return;
  }

  if (has("--any")) {
    const q = arg("--any");
    if (!q) { console.error("# --any requires a query"); return; }
    let found = resolveFile(keys, filesObj, q);
    if (found) {
      console.log(fileBlock(q, found));
      return;
    }
    const lowered = q.toLowerCase();
    const symMatch = (rankedSymbols || []).filter((s) => s.name.toLowerCase().includes(lowered));
    if (symMatch.length) {
      const byFile2 = new Map();
      for (const s of symMatch) { if (!byFile2.has(s.file)) byFile2.set(s.file, []); byFile2.get(s.file).push(s); }
      for (const [file, syms] of byFile2) {
        const f = filesObj[file];
        if (!f) continue;
        console.log(fileBlock(file, { ...f, exports: syms }));
      }
      return;
    }
    if (features) {
      for (const [feat, featFiles] of Object.entries(features)) {
        if (feat.toLowerCase().includes(lowered)) {
          for (const ff of featFiles) {
            const f2 = filesObj[ff];
            if (f2) console.log(fileBlock(ff, f2));
          }
          return;
        }
      }
    }
    const content = contentSearch(q);
    if (content) {
      const lines = content.split("\n").slice(0, CONTENT_LINES_LIMIT);
      for (const line of lines) console.log(line);
      return;
    }
    console.log(`# no results for "${q}"`);
    return;
  }

  if (has("--find")) {
    const q = arg("--find");
    if (!q) { console.error("# --find requires a keyword"); return; }
    const lowered = q.toLowerCase();
    const syms = (rankedSymbols || []).filter((s) => s.name.toLowerCase().includes(lowered));
    for (const s of syms) console.log(`${s.file}  ${s.name}  ${s.kind}  (${(s.rank || 0).toFixed(4)})`);
    if (!syms.length) console.log(`# no symbols matching "${q}"`);
    return;
  }

  if (has("--feature")) {
    const q = arg("--feature");
    if (!q || !features) { console.error("# --feature requires a feature name"); return; }
    const lowered = q.toLowerCase();
    for (const [feat, featFiles] of Object.entries(features)) {
      if (feat.toLowerCase().includes(lowered)) {
        for (const ff of featFiles) {
          const f2 = filesObj[ff];
          if (f2) console.log(ff);
        }
      }
    }
    return;
  }

  if (has("--features")) {
    if (!features) { console.log("(no features detected)"); return; }
    for (const feat of Object.keys(features).sort()) console.log(feat);
    return;
  }

  if (has("--relates")) {
    const q = arg("--relates");
    if (!q) { console.error("# --relates requires a file path"); return; }
    const targetKeys = keys.filter((k) => k.includes(q) || k.endsWith(q));
    const related = new Map();
    for (const k of targetKeys) {
      for (const edge of (edges || [])) {
        const [from, to] = edge;
        if (from === k) related.set(to, (related.get(to) || 0) + 1);
        if (to === k) related.set(from, (related.get(from) || 0) + 1);
      }
    }
    const sorted2 = [...related.entries()].sort((a, b) => b[1] - a[1]).slice(0, RELATED_LIMIT);
    if (isJsonOut) {
      console.log(JSON.stringify(sorted2.map(([f]) => f), null, 2));
    } else {
      for (const [f] of sorted2) console.log(f);
      if (!sorted2.length) console.log(`# no related files for "${q}"`);
    }
    return;
  }

  if (has("--print")) {
    const q = arg("--print") || keys[0];
    const f = resolveFile(keys, filesObj, q);
    if (f) {
      process.stdout.write(fileBlock(q, f));
    } else {
      console.log(`# file not found: ${q}`);
    }
    return;
  }

  if (has("--install-skill")) {
    const skillDir = join(process.cwd(), ".claude", "skills");
    mkdirSync(skillDir, { recursive: true });
    const skillContent = `name: agentmap
description: Query the codebase using agentmap — the repo-map tool for TS/JS projects
`;
    writeFileSync(join(skillDir, "agentmap.md"), skillContent);
    console.log("# skill installed to .claude/skills/agentmap.md");
    return;
  }

  if (has("--audit-fixes")) {
    const maps = [MAP, MAP_LEGACY];
    for (const m of maps) {
      if (existsSync(m)) {
        try {
          const data = JSON.parse(readFileSync(m, "utf8"));
          if (data.hubs && Array.isArray(data.hubs)) {
            const fileSet = new Set(Object.keys(data.files || {}));
            data.hubs = data.hubs.filter((h) => fileSet.has(h.file));
            writeFileSync(m, JSON.stringify(data, null, 1) + "\n");
          }
        } catch {}
      }
    }
    console.log("# audit fixes applied");
    return;
  }

  const unknown = args.filter((a) => a.startsWith("--") && !KNOWN.has(a));
  if (unknown.length) {
    console.error(`# unknown flag(s): ${unknown.join(", ")}`);
    process.exit(2);
  }
}
